version: "3.9"
services:
  db:
    image: mysql:latest
    container_name: base_datos
    environment:
      - MYSQL_DATABASE=taller
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db-dump:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
volumes:
  db-dump:
  mysql: